name: upper-build

on: 
    push:
      paths:
        - ".github/workflows/upper-build.yaml"
    workflow_dispatch: #manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: go version